import React ,{ReactNode } from "react";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { languages } from "@/app/i18n/settings";
import { dir } from "i18next";
import BurgerMenu from "./components/global/BurgerMenu/BurgerMenu";
import Navbar from "./components/global/NavBar/Navbar";
import { GetInfoForCustomer } from "./api/info";
import StoreProvider from "./StoreProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  params: {
    locale: string;
  };
  children: ReactNode;
}
 
// export async function getServerSideProps () {
//   return languages.map((lng) => ({ lng }));
// }

export default async function RootLayout({ params: { locale }, children }: RootLayoutProps) {
  const data = await GetInfoForCustomer()
  return (
    <StoreProvider>
    <html lang={locale}  dir={dir(locale)}>
      <body className={inter.className}>
      <div className="absolute ">
            <BurgerMenu />
          </div>
          <div className="fixed lg:relative z-40 bg-white w-full">
            <Navbar data={data?.data?.data} />
          </div>
          {children}
          <div className="">
            {/* <Footer social={data?.data?.data?.social} logo={data?.data?.data?.logo} /> */}
          </div>
        </body>
    </html>
    </StoreProvider>
  );
}
