import React ,{ReactNode } from "react";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { languages } from "@/app/i18n/settings";
import { dir } from "i18next";
import StoreProvider from "./StoreProviders";
import dynamic from 'next/dynamic'
 
const BurgerMenu = dynamic(() => import('./components/global/BurgerMenu/BurgerMenu'), { ssr: false });
const Footer = dynamic(() => import('./components/page/Footer/Footer'), { ssr: false })
const Navbar = dynamic(() => import('./components/global/NavBar/Navbar'), { ssr: false,})



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  params: {
    locale: string;
  };
  children: ReactNode;
}
 
// export async function getServerSideProps () {
//   return languages.map((locale) => ({ locale }));
// }

export default async function RootLayout({ params: { locale }, children }: RootLayoutProps) {
  return (
    <StoreProvider>
    <html lang={locale}  dir={dir(locale)} style={{direction : locale == "ar" ? "rtl" : "ltr"}}>
      <body className={inter.className}>
      <div className="absolute ">
            <BurgerMenu locale={locale} />
          </div>
          <div className="fixed lg:relative z-40 bg-white w-full">
            <Navbar locale={locale} />
          </div>
          {children}
          <div className="">
            <Footer locale={locale} />
          </div>
        </body>
    </html>
    </StoreProvider>
  );
}
